export const MODULES = {
  DASHBOARD: "dashboard",
  ASSETS: "assets",
  DEVICES: "devices",
  ASSET_TRANSFER: "asset-transfer",
  WORK_ORDERS: "work-orders",
  PM: "pm",
  CALIBRATION: "calibration",
  STORE_MASTER: "store-master",
  ITEM_MASTER: "item-master",
  GRN: "grn",
  VENDORS: "vendors",
  REPORTS: "reports",
  COMPLIANCE: "compliance",
  TENANT_ADMIN: "tenant-admin",
  PLATFORM_ADMIN: "platform-admin",
} as const

export const ROUTES = {
  ROOT: "/",
  DASHBOARD: `/${MODULES.DASHBOARD}`,
  ASSETS: `/${MODULES.ASSETS}`,
  ASSETS_CREATE: `/${MODULES.ASSETS}/create`,
  ASSETS_EDIT: (id: string) => `/${MODULES.ASSETS}/edit/${id}`,
  DEVICES: `/${MODULES.DEVICES}`,
  ASSET_TRANSFER: `/${MODULES.ASSET_TRANSFER}`,
  WORK_ORDERS: `/${MODULES.WORK_ORDERS}`,
  PM: `/${MODULES.PM}`,
  CALIBRATION: `/${MODULES.CALIBRATION}`,
  STORE_MASTER: `/${MODULES.STORE_MASTER}`,
  ITEM_MASTER: `/${MODULES.ITEM_MASTER}`,
  GRN: `/${MODULES.GRN}`,
  VENDORS: `/${MODULES.VENDORS}`,
  REPORTS: `/${MODULES.REPORTS}`,
  COMPLIANCE: `/${MODULES.COMPLIANCE}`,
  TENANT_ADMIN: `/${MODULES.TENANT_ADMIN}`,
  PLATFORM_ADMIN: `/${MODULES.PLATFORM_ADMIN}`,
} as const
